### ISSUE TITLE
[R-263] Roadmap - v0.2

### ISSUE THREAD

**Issue by jjmachan** [explodinggradients/ragas#1009]
![image](https://uploads.linear.app/0a832749-6bfc-40ec-ae6f-821fa8081d92/b03fef57-cff5-4cb6-a839-b70fec68562f/8d292dcc-3f04-4f14-8d12-2b743282b435?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzBhODMyNzQ5LTZiZmMtNDBlYy1hZTZmLTgyMWZhODA4MWQ5Mi9iMDNmZWY1Ny1jZmY1LTRjYjYtYTgzOS1iNzBmZWM2ODU2MmYvOGQyOTJkY2MtM2YwNC00ZjE0LThkMTItMmI3NDMyODJiNDM1IiwiaWF0IjoxNzE3NjEwNTA1LCJleHAiOjE3NDkxNDY1MDV9.SDH7eFsST7ZxgcPuIWKvQpbN1UjWI1Cz7rrHqkrfMWE)

- [X] #1010
  - [ ]  Reference free
    - [ ]  Generation
      - [ ]  Summarisation
        - [ ]  Code summary
        - [ ]  Textual summary
  - [ ]  With Reference
    - [X] #1220
      - [ ]  Text
        - [ ]  answer correctness
      - [ ]  Code
      - [ ]  SQL
- [ ] #1011
  - [ ]  make ragas metrics deployable as a server
  - [ ]  make testset generation interactive with an API
- [X] #1018
- [X] #1012
- [X] #1015
- [X] #1016
  - [ ]  for RAG
    - [ ]  structured data
    - [ ]  unstructured data
  - [ ]  Agents simulations
    - [ ]  Based on predefined task & conditions
  - [ ]  State to persist knowledge graphs and results in test generation
- [X] #1237

<sub>From [SyncLinear.com](https://synclinear.com) | [R-263](https://linear.app/exploding-gradients/issue/R-263/roadmap-v02)</sub>

**Comment by rajib76** [comment]
We lack chunk quality metrics as of today. It will be good to see some chunk quality evaluation metrics.

**Comment by jjmachan** [comment]
hey @rajib76, thanks for chipping in 🙂 

could you explain a bit more about how you're measuring quality here? maybe an example too if possible?

**Comment by rajib76** [comment]
One of the hard problem today in RAG is to determine the right size of the chunk. If a chunk talks about multiple concept, it is very difficult to find the most relevant chunk for the question. I was looking for a metrics that will tell that a chunk is atomic and it talks about only one concept. The semantic chunking approach did not work as the embedding model itself has a semantic dissonance.

**Comment by sky-2002** [comment]
@jjmachan @rajib76 metrics like `chunk_attribution` and `chunk_utilization` (as referenced [here](https://docs.rungalileo.io/galileo/gen-ai-studio-products/guardrail-store/chunk-attribution)) could help to quantify chunk quality. We already have relevance scores(from vector DBs or keyword search engines) to measure chunk relevance with respect to the query. But metrics to quantify how much of the chunk was used can be helpful. I can can take this up you find them useful, I found it interesting, could help decide how many chunks to retrieve.

**Comment by rajib76** [comment]
This will be useful Akash.this will help in chunk tuning.

**Comment by Twist333d** [comment]
@jjmachan hey, thanks for the superb library and effort!

I want to use RAGAS to evaluate my open-source RAG application that has it's own custom chunker and retriever. Do you consider feasible adding support for custom-chunks to the synthetic data generator? 

Right now I can't really use ragas fully because I need to rely on the chunks generated by ragas, instead of my own chunker.

**Comment by jjmachan** [comment]
hey @Twist333d - thanks for the kind words ❤️ 
we just revamped the testset generation piece for v0.2 - we just released an beta version - but main version should be out next week

do you want to give that a go?

**Comment by Twist333d** [comment]
yep @jjmachan shoot it of course!

Btw, I've just setup RAGAS to be used with Weave, and another feature request came up - it would be great if you supported a much easier integration with tracing & eval suites such as Weave by W&B.

**Comment by Twist333d** [comment]
Several more feature requests:

1. Allow random or 'smart' sampling of samples to be used to generate questions. For example, I want to generate a test dataset for a set of documents. Depending on the volume (1 page vs 10000 pages), I want to be able to control how / where do the questions come from
2. Async / parallel generation of embeddings
3. Control over how many embeddings are generated for the input file to the dataset generator - as I understand right now it converts all nodes to embeddings which might be too costly or not necessary. For example, if I set test_size==1, why does it convert all nodes to embeddings
